# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund_transfer_app', '0002_auto_20171202_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund_transfer_app.Node'),
        ),
    ]
